### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by john-light** [blockstack/cli-blockstack#19]
I am trying to install the CLI on a Linux Mint 18.3 machine with Node 12.6.0

Getting the following error on running `npm install`:

```
make: Entering directory '/home/user/cli-blockstack/node_modules/tiny-secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/native/addon.o
make: g++: Command not found
secp256k1.target.mk:149: recipe for target 'Release/obj.target/secp256k1/native/addon.o' failed
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 127
make: Leaving directory '/home/user/cli-blockstack/node_modules/tiny-secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/home/user/.nvm/versions/node/v12.6.0/bin/node" "/home/user/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/cli-blockstack/node_modules/tiny-secp256k1
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kantai** [comment]
It looks like `g++` doesn't exist on your system. This library uses a native binding for SECP256k1, which on most Linux distros needs to be compiled.

You need to install `build-essentials` to compile.

**Comment by john-light** [comment]
Thanks @kantai. That did help. I also figured out there were a couple of other problems, namely that I did not yet have blockstack.js installed and I was on the most recent version of node.js instead of the most recent LTS version. Neither of those details were mentioned in the installation instructions in the README file of this repo, so that might be worth documenting to prevent future head-scratching 🙂

**Comment by moxiegirl** [comment]
@john-light Thank you for bringing this to our attention. I have created https://github.com/blockstack/docs.blockstack/issues/320 to address your comment.  Our documentation for installing the cli is here: https://docs.blockstack.org/develop/clidocs#installCommandLine
