### ISSUE TITLE
blockstack-cli balance - Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by Trudko** [blockstack/cli-blockstack#44]
I've installed Blocstack-cli Wallet [per instructions ](https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html). Tried to get balance but got type error instead.

**Step to reproduce**
1. Run npm install -g https://github.com/blockstack/cli-blockstack#feature/stacks-2.0-tx
2. blockstack-cli make_keychain -t
3. Copy keyinfo.address value
4. Run command blockstack-cli balance {addres from step 3} or really any address

**Expected behavior**
Either get balance of the address (0 stx) or at least got user facing error instead of type error

**Environment** 
MacOS Catalina 10.15.4
node v10.15.3

**Additional context**
Errors:
```
TypeError: Cannot read property 'startsWith' of undefined
    at node_fetch_1.default.then.then (/Users/peter/.nvm/versions/node/v10.15.3/lib/node_modules/blockstack-cli/lib/cli.js:1981:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Cannot read property 'startsWith' of undefined
peters-MacBook-Pro:My peter$ blockstack-cli balance 123123
TypeError: Cannot read property 'startsWith' of undefined
    at node_fetch_1.default.then.then (/Users/peter/.nvm/versions/node/v10.15.3/lib/node_modules/blockstack-cli/lib/cli.js:1981:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Cannot read property 'startsWith' of undefined

```

**Comment by Trudko** [comment]
Nvm didn't add -H "http://neon.blockstack.org:20443". Might close if -H is temporary parameter in which case type error doesn't matter.

**Comment by jdbender66** [comment]
I ran into this same issue! My window wasn't large enough so I couldn't see the -H and pointer to neon. Worked once I entered the entire command. Glad to hear you worked through the same obstacle.

**Comment by yknl** [comment]
This should be resolved with latest in https://github.com/blockstack/cli-blockstack/pull/40
