### ISSUE TITLE
blockstack-cli balance error after sending tokens through Faucet 

### ISSUE THREAD

**Issue by kevinghim** [blockstack/cli-blockstack#47]
I've installed blockstack-cli per [instructions](https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html#getting-tokens).

**Steps to reproduce**
After using Faucet to send my stacks address, I'm getting the following error when checking the balance using `blockstack-cli balance ST1616N1TPGYAKGNDM9QVK44R4PWK1GCEWNPR5AWC -H "http://neon.blockstack.org:20443": `

Errors:
```
Error: Bad response status: 400
    at /home/pi/.npm-global/lib/node_modules/blockstack-cli/node_modules/blockstack/lib/network.js:488:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Bad response status: 400
```

**Environment**
- OS: Raspberry Pi 4, ARMv7, Raspbian GNU/Linux 10
- Rust version: 6.14.4
- Node version: 12.16.2
- Version of Stacks: 2.0, Neon testnet

**Comment by yknl** [comment]
Is this 400 error persistent? I just gave the command a try and it works. You might have caught the neon node in the middle of a restart.

**Comment by kevinghim** [comment]
I just tried it again and got the same error.

**Comment by emilencePvtLtd** [comment]
+1 on this issue. getting the same issue.

**Comment by yknl** [comment]
The latest in https://github.com/blockstack/cli-blockstack/pull/40 should resolve this issue.
