### ISSUE TITLE
make_keychain error: Module not found

### ISSUE THREAD

**Issue by agraebe** [blockstack/cli-blockstack#54]
**Describe the bug**
I was trying out the Clarity Hello World tutorial (https://docs.blockstack.org/core/smart/tutorial.html#get-familiar-with-cli-optional) and ran these commands:

```
sudo npm install -g "https://github.com/blockstack/cli-blockstack#feature/stacks-2.0-tx"
blockstack make_keychain -t > new_keychain.txt
```

While the installation seems to work fine, the make_keychain errors out with a `MODULE_NOT_FOUND`:

```
Alexanders-MacBook-Pro:new-cli alexandergraebe$ blockstack make_keychain -t > new_keychain.txt
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '../lib/index'
Require stack:
- /usr/local/lib/node_modules/blockstack-cli/cmd/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockstack-cli/cmd/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/blockstack-cli/cmd/index.js' ]
```

**Comment by f055** [comment]
I have the exact same issue with the `stacks-2.0-tx` branch.

**Comment by reedrosenbluth** [comment]
Was able to reproduce this issue locally. Fixed it by wiping my globally installed npm modules:

```
sudo rm -rf ~/.npm-global/lib/node_modules
```

Then I reinstalled the CLI and it's working.

**Comment by f055** [comment]
Hmm unfortunately for me this didn't help. I removed node_modules, purged and reinstalled npm, reinstalled the cli but the issue persists.

**Comment by f055** [comment]
Simply clearing the `node_modules` wasn't enough for my server. I was able to get the `blockstack-cli make_keychain` to run without problems by installing nodejs and npm via NVM (Node Version Manager), meaning:

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm install node
npm install -g https://github.com/blockstack/cli-blockstack#feature/stacks-2.0-tx
blockstack make_keychain -t > new_keychain.txt
```

**Comment by agraebe** [comment]
cc @zone117x
